# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sampling_dpm_C <- function(input_vars, data, hyper_params, params, rmvn, dmvn, rinvg, riwish) {
    .Call('_BayesianITR_sampling_dpm_C', PACKAGE = 'BayesianITR', input_vars, data, hyper_params, params, rmvn, dmvn, rinvg, riwish)
}

sampling_ind_C <- function(input_vars, data, hyper_params, params, rmvn, dmvn, rinvg) {
    .Call('_BayesianITR_sampling_ind_C', PACKAGE = 'BayesianITR', input_vars, data, hyper_params, params, rmvn, dmvn, rinvg)
}

sampling_dp_C <- function(input_vars, data, hyper_params, params, rmvn, dmvn, rinvg, riwish) {
    .Call('_BayesianITR_sampling_dp_C', PACKAGE = 'BayesianITR', input_vars, data, hyper_params, params, rmvn, dmvn, rinvg, riwish)
}

